/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rrlsc;

import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;


/**
 *
 * @author julliancockerell
 */
public class StartUpWindow extends javax.swing.JFrame {

    /**
     * Creates new form StartUpWindow
     */
    public StartUpWindow() {
        initComponents();
        this.setResizable(false);
        
        ImageIcon icons[] = new ImageIcon[8];
        String links[] = new String[]{"/Users/julliancockerell/NetBeansProjects/RRLSC/hshots.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hassists.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hgoals.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hsaves.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hsrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hdrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/htrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hwins.PNG"};
        for(int i = 0; i < 8; i++)
        {
            ImageIcon icon = new ImageIcon(links[i]);
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
            icons[i] = new ImageIcon(newimg);
        }
        dis1.setIcon(icons[0]);
        dis2.setIcon(icons[1]);
        dis3.setIcon(icons[2]);
        dis4.setIcon(icons[3]);
        dis5.setIcon(icons[4]);
        dis6.setIcon(icons[5]);
        dis7.setIcon(icons[6]);
        dis8.setIcon(icons[7]);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        StartPanel = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        GamesPlayed = new javax.swing.JLabel();
        WinP = new javax.swing.JLabel();
        dis1 = new javax.swing.JLabel();
        dis2 = new javax.swing.JLabel();
        dis3 = new javax.swing.JLabel();
        dis4 = new javax.swing.JLabel();
        dis5 = new javax.swing.JLabel();
        dis6 = new javax.swing.JLabel();
        dis7 = new javax.swing.JLabel();
        dis8 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setSize(new java.awt.Dimension(894, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 60, 40));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        ID.setText("ID");

        GamesPlayed.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        GamesPlayed.setText("Games Played");

        WinP.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        WinP.setText("Win %");

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GamesPlayed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(WinP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WinP))
                    .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ID)
                        .addComponent(GamesPlayed)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );

        getContentPane().add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, 40));

        dis1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "shots");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        dis2.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "assists");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        dis3.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "goals");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        dis4.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "saves");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        dis5.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "srankpoints");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        dis6.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "drankpoints");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        dis7.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "trankpoints");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, -1, -1));

        dis8.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "wins");
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        getContentPane().add(dis8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrlsc/RoostaStatCenterResize.png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(864, 473));
        Logo.setMinimumSize(new java.awt.Dimension(864, 473));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 250));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 500, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        
        ImageIcon icons[] = new ImageIcon[8];
        String links[] = new String[]{"/Users/julliancockerell/NetBeansProjects/RRLSC/shots.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/assists.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/goals.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/saves.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/srankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/drankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/trankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/wins.PNG"};
        for(int i = 0; i < 8; i++)
        {
            ImageIcon icon = new ImageIcon(links[i]);
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
            icons[i] = new ImageIcon(newimg);
        }
        dis1.setIcon(icons[0]);
        dis2.setIcon(icons[1]);
        dis3.setIcon(icons[2]);
        dis4.setIcon(icons[3]);
        dis5.setIcon(icons[4]);
        dis6.setIcon(icons[5]);
        dis7.setIcon(icons[6]);
        dis8.setIcon(icons[7]);
        
    }//GEN-LAST:event_StartButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUpWindow().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GamesPlayed;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton StartButton;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel WinP;
    private javax.swing.JLabel dis1;
    private javax.swing.JLabel dis2;
    private javax.swing.JLabel dis3;
    private javax.swing.JLabel dis4;
    private javax.swing.JLabel dis5;
    private javax.swing.JLabel dis6;
    private javax.swing.JLabel dis7;
    private javax.swing.JLabel dis8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
