/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rrlsc;

import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import java.awt.Color;

/**
 *
 * @author julliancockerell
 */
public class StartUpWindow extends javax.swing.JFrame {

    boolean startTriggered;
    
    public StartUpWindow() {
        initComponents();
        startTriggered = false;
        Color bGround = new Color(252, 239, 219);
        Color startColor = new Color(196,123,73);
        Color graphColor = new Color(249, 206, 130);
        
        this.StartPanel.setBackground(graphColor);
        this.getContentPane().setBackground(bGround);
        this.GraphPanel.setBackground(graphColor);
        this.setResizable(false);
        
        ImageIcon icons[] = new ImageIcon[8];
        String links[] = new String[]{"/Users/julliancockerell/NetBeansProjects/RRLSC/hshots.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hassists.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hgoals.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hsaves.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hsrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hdrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/htrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hwins.PNG"};
        for(int i = 0; i < 8; i++)
        {
            ImageIcon icon = new ImageIcon(links[i]);
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
            icons[i] = new ImageIcon(newimg);
        }
        dis1.setIcon(icons[0]);
        dis2.setIcon(icons[1]);
        dis3.setIcon(icons[2]);
        dis4.setIcon(icons[3]);
        dis5.setIcon(icons[4]);
        dis6.setIcon(icons[5]);
        dis7.setIcon(icons[6]);
        dis8.setIcon(icons[7]);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        StartPanel = new RoundedPanel(4);
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        GamesPlayed = new javax.swing.JLabel();
        WinP = new javax.swing.JLabel();
        screenHolder = new javax.swing.JLabel();
        GraphPanel = new RoundedPanel(4);
        dis1 = new javax.swing.JLabel();
        dis2 = new javax.swing.JLabel();
        dis3 = new javax.swing.JLabel();
        dis4 = new javax.swing.JLabel();
        dis5 = new javax.swing.JLabel();
        dis6 = new javax.swing.JLabel();
        dis7 = new javax.swing.JLabel();
        dis8 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        winDisplay = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        tf9 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 216, 158));
        setSize(new java.awt.Dimension(894, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 60, 40));

        StartPanel.setBackground(new java.awt.Color(0, 0, 0));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        ID.setText("ID");

        GamesPlayed.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        GamesPlayed.setText("Games Played");

        WinP.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        WinP.setText("Win %");

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GamesPlayed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(WinP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WinP))
                    .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ID)
                        .addComponent(GamesPlayed)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );

        getContentPane().add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 10, 380, 40));
        getContentPane().add(screenHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 30, 20));

        GraphPanel.setBackground(new java.awt.Color(0, 0, 0));
        GraphPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dis1.setBackground(new java.awt.Color(255, 255, 255));
        dis1.setForeground(new java.awt.Color(255, 255, 255));
        dis1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "shots");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        GraphPanel.add(dis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 150));

        dis2.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "assists");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis2.setBackground(new java.awt.Color(255, 255, 255));
        dis2.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 150, 150));

        dis3.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "goals");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis3.setBackground(new java.awt.Color(255, 255, 255));
        dis3.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 150, 150));

        dis4.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "saves");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis4.setBackground(new java.awt.Color(255, 255, 255));
        dis4.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, 150));

        dis5.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "srankpoints");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis5.setBackground(new java.awt.Color(255, 255, 255));
        dis5.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 150));

        dis6.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "drankpoints");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis6.setBackground(new java.awt.Color(255, 255, 255));
        dis6.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, 150));

        dis7.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "trankpoints");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis7.setBackground(new java.awt.Color(255, 255, 255));
        dis7.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 150, 150));

        dis8.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "wins");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis8.setBackground(new java.awt.Color(255, 255, 255));
        dis8.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 150, 150));

        getContentPane().add(GraphPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 700, 360));

        Logo.setBackground(new java.awt.Color(255, 216, 158));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrlsc/RoostaStatCenterResize2.png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(864, 473));
        Logo.setMinimumSize(new java.awt.Dimension(864, 473));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 500));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        winDisplay.setText("jTextField4");
        jPanel1.add(winDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        tf5.setText("jTextField5");
        jPanel1.add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        tf6.setText("jTextField6");
        jPanel1.add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        tf7.setText("jTextField7");
        jPanel1.add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        tf8.setText("jTextField8");
        jPanel1.add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        tf9.setText("jTextField9");
        jPanel1.add(tf9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jTextField4.setText("jTextField4");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jTextField5.setText("jTextField5");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jTextField6.setText("jTextField6");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 130, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        if(!startTriggered)
        {
            startTriggered = true;
            ImageIcon icons[] = new ImageIcon[8];
            String links[] = new String[]{"/Users/julliancockerell/NetBeansProjects/RRLSC/shots.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/assists.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/goals.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/saves.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/srankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/drankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/trankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/wins.PNG"};
            for(int i = 0; i < 8; i++)
            {
                ImageIcon icon = new ImageIcon(links[i]);
                Image img = icon.getImage(); 
                Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
                icons[i] = new ImageIcon(newimg);
            }
            dis1.setIcon(icons[0]);
            dis2.setIcon(icons[1]);
            dis3.setIcon(icons[2]);
            dis4.setIcon(icons[3]);
            dis5.setIcon(icons[4]);
            dis6.setIcon(icons[5]);
            dis7.setIcon(icons[6]);
            dis8.setIcon(icons[7]);
        }
        
    }//GEN-LAST:event_StartButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartUpWindow().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GamesPlayed;
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton StartButton;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel WinP;
    private javax.swing.JLabel dis1;
    private javax.swing.JLabel dis2;
    private javax.swing.JLabel dis3;
    private javax.swing.JLabel dis4;
    private javax.swing.JLabel dis5;
    private javax.swing.JLabel dis6;
    private javax.swing.JLabel dis7;
    private javax.swing.JLabel dis8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel screenHolder;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    private javax.swing.JTextField tf9;
    private javax.swing.JTextField winDisplay;
    // End of variables declaration//GEN-END:variables
}
