/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rrlsc;

import java.awt.Image;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import java.awt.Color;

/**
 *
 * @author julliancockerell
 */
public class StartUpWindow extends javax.swing.JFrame {

    boolean startTriggered;
    RecordMap accessRecord;
    
    public StartUpWindow() {
        RecordMap records = new RecordMap();
        records.setTemplateData();
        records.serializeMap(records.recordMap);
        records.genAllImages();
        accessRecord = records;
        initComponents();
        startTriggered = false;
        Color bGround = new Color(252, 239, 219);
        Color startColor = new Color(196,123,73);
        Color graphColor = new Color(249, 206, 130);
        
        this.StartPanel.setBackground(graphColor);
        this.getContentPane().setBackground(bGround);
        this.GraphPanel.setBackground(graphColor);
        this.setResizable(false);
        
        ImageIcon icons[] = new ImageIcon[8];
        String links[] = new String[]{"/Users/julliancockerell/NetBeansProjects/RRLSC/hshots.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hassists.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hgoals.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hsaves.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hsrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hdrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/htrankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/hwins.PNG"};
        for(int i = 0; i < 8; i++)
        {
            ImageIcon icon = new ImageIcon(links[i]);
            Image img = icon.getImage(); 
            Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
            icons[i] = new ImageIcon(newimg);
        }
        dis1.setIcon(icons[0]);
        dis2.setIcon(icons[1]);
        dis3.setIcon(icons[2]);
        dis4.setIcon(icons[3]);
        dis5.setIcon(icons[4]);
        dis6.setIcon(icons[5]);
        dis7.setIcon(icons[6]);
        dis8.setIcon(icons[7]);
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        StartPanel = new RoundedPanel(4);
        idEntry = new javax.swing.JTextField();
        gpEntry = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        GamesPlayed = new javax.swing.JLabel();
        WinP = new javax.swing.JLabel();
        screenHolder = new javax.swing.JLabel();
        GraphPanel = new RoundedPanel(4);
        dis1 = new javax.swing.JLabel();
        dis2 = new javax.swing.JLabel();
        dis3 = new javax.swing.JLabel();
        dis4 = new javax.swing.JLabel();
        dis5 = new javax.swing.JLabel();
        dis6 = new javax.swing.JLabel();
        dis7 = new javax.swing.JLabel();
        dis8 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        statPanel = new javax.swing.JPanel();
        wins = new javax.swing.JTextField();
        goals = new javax.swing.JTextField();
        mvps = new javax.swing.JTextField();
        saves = new javax.swing.JTextField();
        shots = new javax.swing.JTextField();
        assists = new javax.swing.JTextField();
        solorp = new javax.swing.JTextField();
        duorp = new javax.swing.JTextField();
        stanrp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 216, 158));
        setSize(new java.awt.Dimension(894, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StartButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 60, 40));

        StartPanel.setBackground(new java.awt.Color(153, 153, 153));

        idEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEntryActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        ID.setText("ID");

        GamesPlayed.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        GamesPlayed.setText("Games Played");

        WinP.setFont(new java.awt.Font("Adobe Fan Heiti Std", 1, 13)); // NOI18N
        WinP.setText("Win %");

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GamesPlayed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(WinP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(WinP))
                    .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ID)
                        .addComponent(GamesPlayed)
                        .addComponent(gpEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );

        getContentPane().add(StartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 10, 380, 40));
        getContentPane().add(screenHolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, 30, 20));

        GraphPanel.setBackground(new java.awt.Color(204, 204, 204));
        GraphPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dis1.setBackground(new java.awt.Color(255, 255, 255));
        dis1.setForeground(new java.awt.Color(255, 255, 255));
        dis1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "shots");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        GraphPanel.add(dis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 150));

        dis2.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "assists");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis2.setBackground(new java.awt.Color(255, 255, 255));
        dis2.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 150, 150));

        dis3.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "goals");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis3.setBackground(new java.awt.Color(255, 255, 255));
        dis3.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 150, 150));

        dis4.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "saves");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis4.setBackground(new java.awt.Color(255, 255, 255));
        dis4.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, 150));

        dis5.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "srankpoints");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis5.setBackground(new java.awt.Color(255, 255, 255));
        dis5.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 150));

        dis6.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "drankpoints");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis6.setBackground(new java.awt.Color(255, 255, 255));
        dis6.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 150, 150));

        dis7.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "trankpoints");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis7.setBackground(new java.awt.Color(255, 255, 255));
        dis7.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 150, 150));

        dis8.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(startTriggered){GraphWindow gWin = new GraphWindow(StartUpWindow.this, true, "wins");}
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        dis8.setBackground(new java.awt.Color(255, 255, 255));
        dis8.setForeground(new java.awt.Color(255, 255, 255));
        GraphPanel.add(dis8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 150, 150));

        getContentPane().add(GraphPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 700, 360));

        Logo.setBackground(new java.awt.Color(255, 216, 158));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rrlsc/RoostaStatCenterResize2.png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(864, 473));
        Logo.setMinimumSize(new java.awt.Dimension(864, 473));
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 500, 500));

        statPanel.setBackground(new java.awt.Color(153, 153, 153));

        wins.setText("jTextField4");

        goals.setText("jTextField5");

        mvps.setText("jTextField6");

        saves.setText("jTextField7");

        shots.setText("jTextField8");

        assists.setText("jTextField9");

        solorp.setText("jTextField4");

        duorp.setText("jTextField5");

        stanrp.setText("jTextField6");
        stanrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stanrpActionPerformed(evt);
            }
        });

        jLabel1.setText("Wins");

        jLabel2.setText("Goals");

        jLabel3.setText("MVPs");

        jLabel4.setText("Saves");

        jLabel5.setText("Shots");

        jLabel6.setText("Assists");

        jLabel7.setText("Solo RP");

        jLabel8.setText("Duo RP");

        jLabel9.setText("Stan RP");

        javax.swing.GroupLayout statPanelLayout = new javax.swing.GroupLayout(statPanel);
        statPanel.setLayout(statPanelLayout);
        statPanelLayout.setHorizontalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wins, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvps, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saves, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shots, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assists, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solorp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(duorp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stanrp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        statPanelLayout.setVerticalGroup(
            statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mvps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(14, 14, 14)
                .addGroup(statPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stanrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        getContentPane().add(statPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 150, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        if(!startTriggered)
        {
            startTriggered = true;
            ImageIcon icons[] = new ImageIcon[8];
            String links[] = new String[]{"/Users/julliancockerell/NetBeansProjects/RRLSC/shots.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/assists.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/goals.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/saves.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/srankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/drankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/trankpoints.PNG", "/Users/julliancockerell/NetBeansProjects/RRLSC/wins.PNG"};
            for(int i = 0; i < 8; i++)
            {
                ImageIcon icon = new ImageIcon(links[i]);
                Image img = icon.getImage(); 
                Image newimg = img.getScaledInstance(150, 150, java.awt.Image.SCALE_SMOOTH);
                icons[i] = new ImageIcon(newimg);
            }
            dis1.setIcon(icons[0]);
            dis2.setIcon(icons[1]);
            dis3.setIcon(icons[2]);
            dis4.setIcon(icons[3]);
            dis5.setIcon(icons[4]);
            dis6.setIcon(icons[5]);
            dis7.setIcon(icons[6]);
            dis8.setIcon(icons[7]);
            int gamesPlayed = Integer.parseInt(gpEntry.getText());
            wins.setText(accessRecord.avgStats[0] + " %");
            
        }
        
    }//GEN-LAST:event_StartButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void idEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEntryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEntryActionPerformed

    private void stanrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stanrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stanrpActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new StartUpWindow().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GamesPlayed;
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton StartButton;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JLabel WinP;
    private javax.swing.JTextField assists;
    private javax.swing.JLabel dis1;
    private javax.swing.JLabel dis2;
    private javax.swing.JLabel dis3;
    private javax.swing.JLabel dis4;
    private javax.swing.JLabel dis5;
    private javax.swing.JLabel dis6;
    private javax.swing.JLabel dis7;
    private javax.swing.JLabel dis8;
    private javax.swing.JTextField duorp;
    private javax.swing.JTextField goals;
    private javax.swing.JTextField gpEntry;
    private javax.swing.JTextField idEntry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mvps;
    private javax.swing.JTextField saves;
    private javax.swing.JLabel screenHolder;
    private javax.swing.JTextField shots;
    private javax.swing.JTextField solorp;
    private javax.swing.JTextField stanrp;
    private javax.swing.JPanel statPanel;
    private javax.swing.JTextField wins;
    // End of variables declaration//GEN-END:variables
}
